DEMO01 = "01 - Initialization/"
DEMO02 = "02 - Resources/"
DEMO03 = "03 - Input/"
DEMO04 = "04 - Screen Settings/"
DEMO05 = "05 - Primitives/"
DEMO06 = "06 - Text/"
DEMO07 = "07 - Sprites"
DEMO08 = "08 - Sprite Engine/"
DEMO09 = "09 - Sprite Engine(Classes)/"
DEMO10 = "10 - Tiles/"
DEMO11 = "11 - Grid/"
DEMO12 = "12 - Render into Texture/"
DEMO13 = "13 - Particles/"
DEMO14 = "14 - Sound/"
DEMO15 = "15 - Video/"
DEMO16 = "16 - Physics/"

win32:
	make -C $(DEMO01) win32
	make -C $(DEMO02) win32
	make -C $(DEMO03) win32
	make -C $(DEMO04) win32
	make -C $(DEMO05) win32
	make -C $(DEMO06) win32
	make -C $(DEMO07) win32
	make -C $(DEMO08) win32
	make -C $(DEMO09) win32
	make -C $(DEMO10) win32
	make -C $(DEMO11) win32
	make -C $(DEMO12) win32
	make -C $(DEMO13) win32
	make -C $(DEMO14) win32
	make -C $(DEMO15) win32
	make -C $(DEMO16) win32

win64:
	make -C $(DEMO01) win64
	make -C $(DEMO02) win64
	make -C $(DEMO03) win64
	make -C $(DEMO04) win64
	make -C $(DEMO05) win64
	make -C $(DEMO06) win64
	make -C $(DEMO07) win64
	make -C $(DEMO08) win64
	make -C $(DEMO09) win64
	make -C $(DEMO10) win64
	make -C $(DEMO11) win64
	make -C $(DEMO12) win64
	make -C $(DEMO13) win64
	make -C $(DEMO14) win64
	make -C $(DEMO15) win64
	make -C $(DEMO16) win64

clean:
	make -C $(DEMO01) clean
	make -C $(DEMO02) clean
	make -C $(DEMO03) clean
	make -C $(DEMO04) clean
	make -C $(DEMO05) clean
	make -C $(DEMO06) clean
	make -C $(DEMO07) clean
	make -C $(DEMO08) clean
	make -C $(DEMO09) clean
	make -C $(DEMO10) clean
	make -C $(DEMO11) clean
	make -C $(DEMO12) clean
	make -C $(DEMO13) clean
	make -C $(DEMO14) clean
	make -C $(DEMO15) clean
	make -C $(DEMO16) clean
