DEMO01 = "01 - Initialization/"
DEMO02 = "02 - Input/"
DEMO03 = "03 - Primitives 2D/"
DEMO04 = "04 - Text/"
DEMO05 = "05 - Sprites 2D/"
DEMO06 = "06 - SEngine 2D/"
DEMO07 = "07 - SEngine 2D(OOP)/"
DEMO08 = "08 - Sound/"
DEMO09 = "09 - Render to Texture/"
DEMO10 = "10 - Particles 2D/"
DEMO11 = "11 - Physics 2D/"

all:
	make -C $(DEMO01)
	make -C $(DEMO02)
	make -C $(DEMO03)
	make -C $(DEMO04)
	make -C $(DEMO05)
	make -C $(DEMO06)
#	make -C $(DEMO07)
	make -C $(DEMO08)
#	make -C $(DEMO09)
#	make -C $(DEMO10)
#	make -C $(DEMO11)

linux32:
	make -C $(DEMO01) linux32
	make -C $(DEMO02) linux32
	make -C $(DEMO03) linux32
	make -C $(DEMO04) linux32
	make -C $(DEMO05) linux32
	make -C $(DEMO06) linux32
#	make -C $(DEMO07) linux32
	make -C $(DEMO08) linux32
#	make -C $(DEMO09) linux32
#	make -C $(DEMO10) linux32
#	make -C $(DEMO11) linux32

win32:
	make -C $(DEMO01) win32
	make -C $(DEMO02) win32
	make -C $(DEMO03) win32
	make -C $(DEMO04) win32
	make -C $(DEMO05) win32
	make -C $(DEMO06) win32
#	make -C $(DEMO07) win32
	make -C $(DEMO08) win32
#	make -C $(DEMO09) win32
#	make -C $(DEMO10) win32
#	make -C $(DEMO11) win32

win64:
	make -C $(DEMO01) win64
	make -C $(DEMO02) win64
	make -C $(DEMO03) win64
	make -C $(DEMO04) win64
	make -C $(DEMO05) win64
	make -C $(DEMO06) win64
#	make -C $(DEMO07) win64
	make -C $(DEMO08) win64
#	make -C $(DEMO09) win64
#	make -C $(DEMO10) win64
#	make -C $(DEMO11) win64

macos:
	make -C $(DEMO01) macos
	make -C $(DEMO02) macos
	make -C $(DEMO03) macos
	make -C $(DEMO04) macos
	make -C $(DEMO05) macos
	make -C $(DEMO06) macos
#	make -C $(DEMO07) macos
	make -C $(DEMO08) macos
#	make -C $(DEMO09) macos
#	make -C $(DEMO10) macos
#	make -C $(DEMO11) macos

clean:
	make -C $(DEMO01) clean
	make -C $(DEMO02) clean
	make -C $(DEMO03) clean
	make -C $(DEMO04) clean
	make -C $(DEMO05) clean
	make -C $(DEMO06) clean
#	make -C $(DEMO07) clean
	make -C $(DEMO08) clean
#	make -C $(DEMO09) clean
#	make -C $(DEMO10) clean
#	make -C $(DEMO11) clean
