# copy libraries
cp ../../../../bin/Android/armv5/libchipmunk.so ../libs/armeabi/
cp ../../../../bin/Android/armv5/libopenal.so ../libs/armeabi/
cp ../../../../bin/Android/armv5/libzenjpeg.so ../libs/armeabi/
# copy resources
cp ../../../../bin/data/click.wav ../assets
cp ../../../../bin/data/music.ogg ../assets
cp ../../../../bin/data/audio-stop.png ../assets
cp ../../../../bin/data/audio-play.png ../assets
cp ../../../../bin/data/font* ../assets