win32:
	i486-mingw32-gcc jpeg_helper.c -c -oi386-win32/jpeg_helper.o -O2 -s -ffast-math -std=c99 -march=i686

win64:
	x86_64-w64-mingw32-gcc jpeg_helper.c -c -ox86_64-win64/jpeg_helper.o -O2 -s -ffast-math -std=c99
