DEMO01 = "01 - Initialization/FreePascal/"
DEMO02 = "02 - Input/FreePascal/"
DEMO03 = "03 - Primitives 2D/FreePascal/"
DEMO04 = "04 - Text/FreePascal/"
DEMO05 = "05 - Sprites 2D/FreePascal/"
DEMO06 = "06 - SEngine 2D/FreePascal/"
DEMO07 = "07 - SEngine 2D(OOP)/FreePascal/"
DEMO08 = "08 - Sound/FreePascal/"
DEMO09 = "09 - Render to Texture/FreePascal/"
DEMO10 = "10 - Physics Simple/FreePascal/"

all:
	make -C $(DEMO01)
	make -C $(DEMO02)
	make -C $(DEMO03)
	make -C $(DEMO04)
	make -C $(DEMO05)
	make -C $(DEMO06)
	make -C $(DEMO07)
	make -C $(DEMO08)
	make -C $(DEMO09)
	make -C $(DEMO10)

win32:
	make -C $(DEMO01) win32
	make -C $(DEMO02) win32
	make -C $(DEMO03) win32
	make -C $(DEMO04) win32
	make -C $(DEMO05) win32
	make -C $(DEMO06) win32
	make -C $(DEMO07) win32
	make -C $(DEMO08) win32
	make -C $(DEMO09) win32
	make -C $(DEMO10) win32

clean:
	make -C $(DEMO01) clean
	make -C $(DEMO02) clean
	make -C $(DEMO03) clean
	make -C $(DEMO04) clean
	make -C $(DEMO05) clean
	make -C $(DEMO06) clean
	make -C $(DEMO07) clean
	make -C $(DEMO08) clean
	make -C $(DEMO09) clean
	make -C $(DEMO10) clean
